services:
  app:
    build: .
    image: gdns
    command: /docker-gdns
    ports:
      - "53:53/udp"
    depends_on:
      - redis
      - rabbitmq
    environment:
      - BLOCKLIST_DB=/app/data/blocklist.db
      - REDIS_URL=redis:6379
    restart: unless-stopped

  test:
    image: gdns
    command: go test ./test

  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6378:6379"
