services:
  app:
    build: .
    image: gdns
    command: /docker-gdns
    ports:
      - "53:5555/udp"
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    environment:
      - SQLITE_URL=/app/data/blocklist.db
      - SQLITE_BLOCKLIST=/app/data/blocked_domains.txt
      - REDIS_URL=redis:6379
      - UDP_PORT=:5555
    restart: unless-stopped

  test:
    image: gdns
    command:
      [
        "/bin/sh",
        "-c",
        "go test ./test/unit/... && go test ./test/fuzz/... -fuzz=FuzzParseAnswer -fuzztime=30s && go test ./test/fuzz/... -fuzz=FuzzDnsParse -fuzztime=30s",
      ]
  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6378:6379"

  test_unit:
    image: gdns
    command: ["/bin/sh", "-c", "go test ./test/unit/... "]

  test_int:
    image: gdns
    command: ["/bin/sh", "-c", "go test ./test/integration/... "]
  test_fuzz:
    image: gdns
    command:
      [
        "/bin/sh",
        "-c",
        "go test ./test/fuzz/... -fuzz=FuzzParseAnswer -fuzztime=30s && go test ./test/fuzz/... -fuzz=FuzzDnsParse -fuzztime=30s",
      ]
