services:
  app:
    build: .
    image: gdns
    command: /docker-gdns
    ports:
      - "53:5555/udp"
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    environment:
      - SQLITE_URL=/app/data/blocklist.db
      - SQLITE_BLOCKLIST=/app/data/blocked_domains.txt
      - REDIS_URL=redis:6379
      - UDP_PORT=:5555
    restart: unless-stopped

  test:
    image: gdns
    command: go test ./test/...

  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6378:6379"
